# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('mentor_name', models.CharField(max_length=50, verbose_name='Mentor')),
                ('division', models.CharField(max_length=100, verbose_name='Divize')),
                ('pros_of_mentor', models.CharField(max_length=2000, verbose_name='Mentorovy přednosti')),
                ('position_name', models.CharField(max_length=50, verbose_name='Jméno pozice')),
                ('position_description', models.CharField(max_length=2000, verbose_name='Popis pozice')),
                ('project', models.CharField(max_length=1000, verbose_name='Projekt')),
                ('benefit_for_intern', models.CharField(max_length=1000, verbose_name='Výhody pro stážistu')),
                ('requirements', models.CharField(max_length=1000, verbose_name='Požadavky')),
                ('notes', models.CharField(max_length=1000, verbose_name='Poznámky')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Datum registrace')),
            ],
        ),
    ]
