# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=50)),
                ('learned_from', models.CharField(choices=[('K', 'Od kamaráda'), ('V', 'Z veletrhu'), ('F', 'Z Facebooku')], max_length=1)),
                ('resume', models.FileField(upload_to='')),
                ('cover_letter', models.FileField(upload_to='')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('first_interview_date', models.DateField()),
                ('second_interview_date', models.DateField()),
                ('wanted_boarding_date', models.DateField()),
                ('real_boarding_date', models.DateField()),
                ('mentor', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('assigned_coordinator', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('interests', models.ManyToManyField(to='positions.Position')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.Intern'),
        ),
    ]
