# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('obligation', models.CharField(max_length=80)),
                ('interests', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
